### PR TITLE
Build release packages for Windows, Linux and macOS in the CI

### PR DESCRIPTION
**Pull request by trufae**
Screenshot 2021-02-03 at 01 08 57
Screenshot 2021-02-03 at 01 17 39

### CODE REVIEW

**Review by wargio — APPROVED** [review]

**Comment by wargio** [comment]
those packages should have the version in their name

**Comment by trufae** [comment]
Like this?
Screenshot 2021-02-03 at 01 29 05

**Comment by trufae** [comment]
Done https://github.com/wargio/r2dec-js/actions/runs/532391106#artifacts

**Comment by trufae** [comment]
After merging this i would remove the other gha tasks and the travis which is slower

**Comment by wargio** [comment]
WTF. why travis is there? i deleted it.

**Comment by trufae** [comment]
Thanks!!

**Pull request merged**
