### PR TITLE
Fixes #97  - pddf - decompile all functions

### LINKED ISSUE #97: Command to dump pdd for the whole file (all functions)
Add a command to dump pdd for the whole file (all functions)

### PR DESCRIPTION
**Pull request by wargio**
Fixes #97 

essentially decompiles all functions.

### CODE REVIEW

**Comment by wargio** [comment]
```
[0x080483e0]> pddf
/* r2dec pseudo code output */
/* /home/gdgrazioli/private/radare2-regressions/bins/elf/crackme0x00b */
#include <stdint.h>
 

/* name: entry0 @ 0x80483e0 */
void entry0 (void) {
    /* [13] -r-x section size 460 named .text */
    ebp = 0;
    ecx = esp;
    return libc_start_main (main, esi, ecx, sym.__libc_csu_init, sym.__libc_csu_fini, edx, esp);
}

/* name: sym.__do_global_dtors_aux @ 0x8048410 */
int32_t do_global_dtors_aux (void) {
    if (*(obj.completed.6086) != 0) {
        goto label_0;
    }
    eax = *(obj.dtor_idx.6088);
    ebx = obj.__DTOR_END;
    ebx -= obj.__DTOR_LIST;
    ebx >>= 2;
    ebx--;
    if (eax >= ebx) {
        goto label_1;
    }
    do {
        eax++;
        *(obj.dtor_idx.6088) = eax;
        uint32_t (*eax*4 + obj.__DTOR_LIST)() ();
        eax = *(obj.dtor_idx.6088);
    } while (eax < ebx);
label_1:
    *(obj.completed.6086) = 1;
label_0:
    return eax;
}

/* name: sym.frame_dummy @ 0x8048470 */
int32_t frame_dummy (void) {
    eax = *(obj.__JCR_LIST);
    if (eax != 0) {
        eax = 0;
        if (eax == 0) {
            goto label_2;
        }
        void (*eax)(void) (obj.__JCR_LIST);
    }
label_2:
    return eax;
}

/* name: sym.__do_global_ctors_aux @ 0x8048580 */
int32_t do_global_ctors_aux (void) {
    eax = .ctors;
    if (eax == -1) {
        goto label_3;
    }
    ebx = .ctors;
    do {
        ebx -= 4;
        void (*eax)() ();
        eax = *(ebx);
    } while (eax != -1);
label_3:
    return eax;
}

/* name: sym.__libc_csu_fini @ 0x8048570 */
void libc_csu_fini (void) {
}

/* name: sym.__i686.get_pc_thunk.bx @ 0x8048572 */
void i686_get_pc_thunk_bx (void) {
    ebx = *(esp);
}

/* name: sym._fini @ 0x80485ac */
void fini (void) {
    /* [14] -r-x section size 26 named .fini */
    void (*0x80485b5)(void) (ebx);
    ebx += 0x1a3f;
    _do_global_dtors_aux ();
}

/* name: sym.__libc_csu_init @ 0x8048500 */
uint32_t libc_csu_init (int32_t arg_30h, int32_t arg_34h, int32_t arg_38h) {
    int32_t var_4h;
    int32_t var_8h;
    _i686_get_pc_thunk_bx (ebx, esi, edi);
    ebx += 0x1aeb;
    edi = ebx - 0xe0;
    _init ();
    eax = ebx - 0xe0;
    edi -= eax;
    edi >>= 2;
    if (edi == 0) {
        goto label_4;
    }
    esi = 0;
    do {
        eax = arg_38h;
        eax = arg_34h;
        uint32_t (*ebx + esi*4 - 0xe0)(void, void, void) (ebp, eax, arg_34h);
        esi++;
    } while (esi != edi);
label_4:
    return eax;
}

/* name: main @ 0x8048494 */
int32_t main (void) {
    wchar_t * s2;
    int32_t var_1ch;
    do {
        eax = "Enter password: ";
        printf (eax);
        eax = 0x80485e1;
        edx = &var_1ch;
        isoc99_scanf (eax, edx);
        eax = &var_1ch;
        eax = wcscmp ("w0wgreat", eax);
        if (eax == 0) {
            puts ("Congrats!");
            eax = 0;
            return eax;
        }
        puts ("Wrong!");
    } while (1);
}

/* name: sym._init @ 0x8048338 */
int32_t init (void) {
    /* [11] -r-x section size 46 named .init */
    void (*0x8048341)(void) (ebx);
    ebx += 0x1cb3;
    eax = *((ebx - 4));
    if (eax != 0) {
        gmon_start_ ();
    }
    frame_dummy ();
    _do_global_ctors_aux ();
    return eax;
}
```

**Comment by wargio** [comment]
```
[0x080483e0]> pddf
/* r2dec pseudo code output */
/* /radare2-regressions/bins/elf/crackme0x00b */
#include <stdint.h>
 

/* name: entry0 @ 0x80483e0 */
void entry0 (void) {
    /* [13] -r-x section size 460 named .text */
    ebp = 0;
    ecx = esp;
    return libc_start_main (main, esi, ecx, sym.__libc_csu_init, sym.__libc_csu_fini, edx, esp);
}

/* name: sym.__do_global_dtors_aux @ 0x8048410 */
int32_t do_global_dtors_aux (void) {
    if (*(obj.completed.6086) != 0) {
        goto label_0;
    }
    eax = *(obj.dtor_idx.6088);
    ebx = obj.__DTOR_END;
    ebx -= obj.__DTOR_LIST;
    ebx >>= 2;
    ebx--;
    if (eax >= ebx) {
        goto label_1;
    }
    do {
        eax++;
        *(obj.dtor_idx.6088) = eax;
        uint32_t (*eax*4 + obj.__DTOR_LIST)() ();
        eax = *(obj.dtor_idx.6088);
    } while (eax < ebx);
label_1:
    *(obj.completed.6086) = 1;
label_0:
    return eax;
}

/* name: sym.frame_dummy @ 0x8048470 */
int32_t frame_dummy (void) {
    eax = *(obj.__JCR_LIST);
    if (eax != 0) {
        eax = 0;
        if (eax == 0) {
            goto label_2;
        }
        void (*eax)(void) (obj.__JCR_LIST);
    }
label_2:
    return eax;
}

/* name: sym.__do_global_ctors_aux @ 0x8048580 */
int32_t do_global_ctors_aux (void) {
    eax = .ctors;
    if (eax == -1) {
        goto label_3;
    }
    ebx = .ctors;
    do {
        ebx -= 4;
        void (*eax)() ();
        eax = *(ebx);
    } while (eax != -1);
label_3:
    return eax;
}

/* name: sym.__libc_csu_fini @ 0x8048570 */
void libc_csu_fini (void) {
}

/* name: sym.__i686.get_pc_thunk.bx @ 0x8048572 */
void i686_get_pc_thunk_bx (void) {
    ebx = *(esp);
}

/* name: sym._fini @ 0x80485ac */
void fini (void) {
    /* [14] -r-x section size 26 named .fini */
    void (*0x80485b5)(void) (ebx);
    ebx += 0x1a3f;
    _do_global_dtors_aux ();
}

/* name: sym.__libc_csu_init @ 0x8048500 */
uint32_t libc_csu_init (int32_t arg_30h, int32_t arg_34h, int32_t arg_38h) {
    int32_t var_4h;
    int32_t var_8h;
    _i686_get_pc_thunk_bx (ebx, esi, edi);
    ebx += 0x1aeb;
    edi = ebx - 0xe0;
    _init ();
    eax = ebx - 0xe0;
    edi -= eax;
    edi >>= 2;
    if (edi == 0) {
        goto label_4;
    }
    esi = 0;
    do {
        eax = arg_38h;
        eax = arg_34h;
        uint32_t (*ebx + esi*4 - 0xe0)(void, void, void) (ebp, eax, arg_34h);
        esi++;
    } while (esi != edi);
label_4:
    return eax;
}

/* name: main @ 0x8048494 */
int32_t main (void) {
    wchar_t * s2;
    int32_t var_1ch;
    do {
        eax = "Enter password: ";
        printf (eax);
        eax = 0x80485e1;
        edx = &var_1ch;
        isoc99_scanf (eax, edx);
        eax = &var_1ch;
        eax = wcscmp ("w0wgreat", eax);
        if (eax == 0) {
            puts ("Congrats!");
            eax = 0;
            return eax;
        }
        puts ("Wrong!");
    } while (1);
}

/* name: sym._init @ 0x8048338 */
int32_t init (void) {
    /* [11] -r-x section size 46 named .init */
    void (*0x8048341)(void) (ebx);
    ebx += 0x1cb3;
    eax = *((ebx - 4));
    if (eax != 0) {
        gmon_start_ ();
    }
    frame_dummy ();
    _do_global_ctors_aux ();
    return eax;
}
```

**Comment by radare** [comment]
I was using “a” for “all” in snow and jadx support. Maybe good to unify this concept too. Can you test the other decompilers ?

**Comment by Maijin** [comment]
For info `| pdda         decompile current function with side assembly`

**Comment by radare** [comment]
Oh right. Maybe i should change that in the other decompilers then

**Comment by wargio** [comment]
yeah, i had to find another letter xD

**Pull request merged**
