### PR TITLE
Fetch libc function argument count info using r2

### PR DESCRIPTION
**Pull request by sivaramaaa**
#### * Before

screenshot from 2018-09-29 01-17-09

#### * After

screenshot from 2018-09-29 01-17-52

### CODE REVIEW

**Comment by elicn** [comment]
What does the new `afcfqj` do?
I found that `afcfj @@@i` provides all the data needed for imports.

**Comment by sivaramaaa** [comment]
hi @elicn , 

`afcfj @@@i` give result like this : 

```
[]
[]
[{"name": "getenv","return": "char *","count": 1,"args":[{"name": "name","type":"const char *"}]}]
[]
[]
[{"name": "raise","return": "int","count": 1,"args":[{"name": "sig","type":"int"}]}]
[{"name": "abort","return": "void","count": 0}]
[]
[{"name": "strncmp","return": "int","count": 3,"args":[{"name": "s1","type":"const char *"},{"name": "s2","type":"const char *"},{"name": "n","type":"size_t"}]}]
[{"name": "_exit","return": "void","count": 1,"args":[{"name": "status","type":"int"}]}]
```
i was not sure how to parse such data in r2dec (if u think it's possible , pls help me out !)
that's why i implemented the command `afcfqj` it gives u a clean array , like this : 

```
[{"name": "getenv","count": 1},{"name": "raise","count": 1},{"name": "free","count": 1},{"name": "abort","count": 0},{"name": "strncmp","count": 3},{"name": "_exit","count": 1},{"name": "strcpy","count": 2},{"name": "isatty","count": 1},{"name": "sigaction","count": 3},{"name": "iswcntrl","count": 1},{"name": "localeconv","count": 0},{"name": "mbstowcs","count": 3},{"name": "textdomain","count": 1},{"name": "fclose","count": 1},{"name": "bindtextdomain","count": 2},{"name": "strlen","count": 1},{"name": "__stack_chk_fail","count": 0},{"name": "mbrtowc","count": 4},{"name": "strchr","count": 2},{"name": "snprintf","count": 4},{"name": "strrchr","count": 2},{"name": "__assert_fail","count": 4},{"name": "memset","count": 3},{"name": "fscanf","count": 3},{"name": "ioctl","count": 2},{"name": "close","count": 1},{"name": "memcmp","count": 3},{"name": "setjmp","count": 1},{"name": "calloc","count": 2},{"name": "strcmp","count": 2},{"name": "signal","count": 2},{"name": "memcpy","count": 3},{"name": "fileno","count": 1},{"name": "fflush","count": 1},{"name": "nl_langinfo","count": 1},{"name": "ungetc","count": 2},{"name": "strcoll","count": 2},{"name": "realloc","count": 2},{"name": "setlocale","count": 2},{"name": "strftime","count": 4},{"name": "memmove","count": 3},{"name": "error","count": 3},{"name": "open","count": 2},{"name": "strtoul","count": 3},{"name": "wcstombs","count": 3},{"name": "exit","count": 1},{"name": "fwrite","count": 4},{"name": "mbsinit","count": 1},{"name": "iswprint","count": 1},{"name": "main","count": 3}]
```

**Comment by wargio** [comment]
Yeah, it is possible to parse it! With a simple regex removing endlines and then parse the big JSON data

**Comment by sivaramaaa** [comment]
> Yeah, it is possible to parse it! With a simple regex removing endlines and then parse the big JSON data

Thanks , let me try with that :+1:

**Comment by wargio** [comment]
@sivaramaaa  https://github.com/wargio/r2dec-js/compare/custom-call

**Pull request merged**
