### PR TITLE
Add support for asm.arch=r2ghidra

### PR DESCRIPTION
**Pull request by trufae**

### CODE REVIEW

**Comment by wargio** [comment]
what is that arch? can you provide a description and a test ?

**Comment by wargio** [comment]
a pddi file should be enough

**Comment by trufae** [comment]
r2ghidra asm and anal plugins uses asm.cpu to define the architecture selected. The arch is taken from a different config var. you must install r2ghidra to test this. But i can confirm this works fine locally. Could be a bit painful to test in ci

**Comment by wargio** [comment]
> r2ghidra asm and anal plugins uses asm.cpu to define the architecture selected. The arch is taken from a different config var. you must install r2ghidra to test this. But i can confirm this works fine locally. Could be a bit painful to test in ci

with pddi output i can test this

**Comment by trufae** [comment]
For an x86-64 hello world: [a.json.zip](https://github.com/wargio/r2dec-js/files/6138253/a.json.zip)

**Comment by trufae** [comment]
ping

**Pull request merged**
