### PR TITLE
Fixes for inr2.js and some undefined dereferences

### PR DESCRIPTION
**Pull request by radare**
* Use r2pipe.quit in a promise-way
* Autodetect arch from current r2 session

	$ r2 -qi inr2.js /bin/ls

### CODE REVIEW

**Comment by radare** [comment]
Right now if you do this in OSX you get an infinite loop because recursion is done wrong, but that's not because of this pr :P

**Comment by wargio** [comment]
Wrong recursion?

**Comment by radare** [comment]
Try it yourself. You can also use chrome devtools to debug the r2 script and see where it loops

**Comment by wargio** [comment]
fixed. was a stupid problem.

**Pull request merged**
