### PR TITLE
Some more goodies to x86

### PR DESCRIPTION
**Pull request by elicn**
More changes to improve readability of deompiled code and some code re-arrangements.

### CODE REVIEW

**Comment by wargio** [comment]
i was thinking to move the operands in the structure into an array. some archs does have several arguments so it would be useful to have them there.

**Comment by elicn** [comment]
Yes, that makes sense.
I'll work on x86.

**Comment by wargio** [comment]
can you test the output of pdd with 
```
mov rax, qword fs:[0x28]
ret
```
and with repe
```javascript
{
              "offset": 4209578,
              "ptr": 98784247836,
              "esil": "edi,[1],esi,[1],==,$z,zf,=,$b8,cf,=,$p,pf,=,$s,sf,=,$o,of,=,ecx,--=,ecx,?{,5,GOTO,}",
              "refptr": true,
              "fcn_addr": 4209520,
              "fcn_last": 4209632,
              "size": 2,
              "opcode": "repe cmpsb byte [esi], byte ptr es:[edi]",
              "disasm": "repe cmpsb byte [esi], byte ptr es:[edi]",
              "bytes": "f3a6",
              "family": "cpu",
              "type": "cmp",
              "type_num": 15,
              "type2_num": 0
}
```

**Comment by elicn** [comment]
We didn't support neither prefixes, segment overrides nor string operations at all, so I am not surprised it breaks: the prefixed instruction ends up in a generic `asm` statement, but the segment override causes the instruction to be shown erroneously.
 I added support for both, but it seems that the disassembler (Capstone?) has a weird bug as it appends "ptr" to the 2nd argument for now visible reason.

**Comment by wargio** [comment]
i've merged them so we can work on it.

**Pull request merged**
